-- MySQL Script generated by MySQL Workbench
-- Tue Jun  4 20:38:31 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema bioblocks
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bioblocks
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bioblocks` DEFAULT CHARACTER SET utf8 ;
USE `bioblocks` ;

-- -----------------------------------------------------
-- Table `bioblocks`.`project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bioblocks`.`project` (
  `id_project` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `creation_date` DATETIME NOT NULL,
  `last_modification` DATETIME NOT NULL,
  `public` TINYINT(1) NOT NULL,
  `owner` INT(11) NOT NULL,
  `xml_file` BLOB NOT NULL,
  PRIMARY KEY (`id_project`),
  UNIQUE INDEX `idproyect_UNIQUE` (`id_project` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 54
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bioblocks`.`projects_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bioblocks`.`projects_group` (
  `id_group` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `owner` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id_group`),
  UNIQUE INDEX `idgroup_UNIQUE` (`id_group` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 18
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bioblocks`.`project_belongs_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bioblocks`.`project_belongs_group` (
  `id_project` INT(11) NOT NULL,
  `id_group` INT(11) NOT NULL,
  PRIMARY KEY (`id_project`, `id_group`),
  INDEX `fk_proyecto_has_GrupoProyectos_GrupoProyectos1_idx` (`id_group` ASC) VISIBLE,
  INDEX `fk_proyecto_has_GrupoProyectos_proyecto1_idx` (`id_project` ASC) VISIBLE,
  CONSTRAINT `fk_proyecto_has_GrupoProyectos_GrupoProyectos1`
    FOREIGN KEY (`id_group`)
    REFERENCES `bioblocks`.`projects_group` (`id_group`),
  CONSTRAINT `fk_proyecto_has_GrupoProyectos_proyecto1`
    FOREIGN KEY (`id_project`)
    REFERENCES `bioblocks`.`project` (`id_project`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bioblocks`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bioblocks`.`user` (
  `id_user` INT(11) NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(45) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` CHAR(60) NOT NULL,
  `email` VARCHAR(60) NOT NULL,
  `creation_date` DATE NOT NULL,
  `user_type` ENUM('professor', 'investigator', 'student', 'standard') NOT NULL DEFAULT 'standard',
  PRIMARY KEY (`id_user`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `bioblocks`.`user_belongs_project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bioblocks`.`user_belongs_project` (
  `id_user` INT(11) NOT NULL,
  `id_project` INT(11) NOT NULL,
  PRIMARY KEY (`id_user`, `id_project`),
  INDEX `fk_usuario_has_proyecto_proyecto1_idx` (`id_project` ASC) VISIBLE,
  INDEX `fk_usuario_has_proyecto_usuario_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_usuario_has_proyecto_proyecto1`
    FOREIGN KEY (`id_project`)
    REFERENCES `bioblocks`.`project` (`id_project`),
  CONSTRAINT `fk_usuario_has_proyecto_usuario`
    FOREIGN KEY (`id_user`)
    REFERENCES `bioblocks`.`user` (`id_user`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
