language: node_js
node_js:
- "8"
sudo: required
addons:
  chrome: stable
cache:
  directories:
  - node_modules

before_install:
# Symlink closure library
- ln -s $(npm root)/google-closure-library ../closure-library

before_script:
  - export DISPLAY=:99.0
  - tests/scripts/setup_linux_env.sh
  - sleep 2

script:
  - set -x
  - npm test
  - cd tests/compile; compile.sh; cd ..